# Generated by Django 6.0.3 on 2026-04-26 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_favorite_unique_together_remove_favorite_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.collection')),
            ],
            options={
                'unique_together': {('collection', 'cat')},
            },
        ),
    ]
