# Generated by Django 6.0.3 on 2026-05-13 19:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_collectioncat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementcat',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='achievementcat',
            name='cat',
        ),
        migrations.AlterUniqueTogether(
            name='collectioncat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='collectioncat',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='collectioncat',
            name='collection',
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['-id'], 'verbose_name': 'Котик', 'verbose_name_plural': 'Котики'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-views_count', '-created_at'], 'verbose_name': 'Подборка', 'verbose_name_plural': 'Подборки'},
        ),
        migrations.AddField(
            model_name='collection',
            name='category',
            field=models.CharField(choices=[('funny', 'Смешные'), ('cute', 'Милашки'), ('sleepy', 'Сонные'), ('active', 'Активные'), ('grumpy', 'Ворчуны'), ('other', 'Другие')], default='other', max_length=32, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='collection',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_collections', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='collection',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='birth_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000, message='Год рождения не может быть раньше 2000'), django.core.validators.MaxValueValidator(2026, message='Год рождения не может быть позже текущего')], verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(max_length=16, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='cats/images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='cats',
            field=models.ManyToManyField(blank=True, related_name='collections', to='cats.cat', verbose_name='Котики в подборке'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название подборки'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='AchievementCat',
        ),
        migrations.DeleteModel(
            name='CollectionCat',
        ),
    ]
