# Generated by Django 5.2.10 on 2026-05-20 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_remove_achievementcat_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birth_year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2026, message='Год рождения не может быть позже текущего')], verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='cats/images/', verbose_name='Фотография'),
        ),
    ]
